### ISSUE TITLE
候选人筛选栏只要年龄，国籍，地点，性别，语言

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#103]
年龄：
低于20
21-39
31-40
41-50
大于51

![屏幕快照 2019-03-28 上午11 56 42](https://user-images.githubusercontent.com/47628230/55129064-b48ec600-5150-11e9-89cd-8afe803c9824.png)

**Comment by jimmywong123** [comment]
搜索框已调整。
![image](https://user-images.githubusercontent.com/42126331/55950685-0fafd500-5c88-11e9-81bc-9db7b13f5236.png)
