### ISSUE TITLE
時常出現500 server reporting 的問題

### ISSUE THREAD

**Issue by kammylam** [UReact/CRM_-feedback#106]
当我开CRM客户，或者职位的时后都时常出现这个问题。例如我想选择那些client没有审批，出多次出现了这个问题。

![1](https://user-images.githubusercontent.com/48010002/55141201-d69a3f80-5174-11e9-8750-31d07dfca8f0.jpg)

**Comment by jimmywong123** [comment]
all client和all position界面已经停用，以后这些操作都在clinet和position界面完成。
