### ISSUE TITLE
建议加一栏可以看到还没有审批的客户（有出广告的）

### ISSUE THREAD

**Issue by kammylam** [UReact/CRM_-feedback#107]
我建议是否可以加一个窗口可以见到那些还没有审批的客户和职位（我意思跟以前一样）。因为现在的方式，我按client 然后再进入HC就会见到全部客户。如果再按 reviewed 就连其他同事Wendy，Milly等等同事都列了出来 （因为他们的客户是不用审批的，所以这里始终都会有好多reviewed的出现）。

以前做法是一按 “All Position",然后选择 ”Reviewed", 我就可以非常清楚看到那个职位，那个客户还没有审批。现在的方式我是好难看到的。（Thomas应该明白我说什么的）
![2](https://user-images.githubusercontent.com/48010002/55200825-08ee8000-51fb-11e9-9380-0a919f6c7020.jpg)

**Comment by jimmywong123** [comment]
现在客户界面在选择reviewed时多了一个客户类别的选项，默认选中hc
![image](https://user-images.githubusercontent.com/42126331/55449924-17280c00-5600-11e9-802b-ca4ab94c81a6.png)
