### ISSUE TITLE
统计数据的搜索，要支持 可以自定义时间段。可以查询任何一个时间段的数据。

### ISSUE THREAD

**Issue by alexwang2019** [UReact/CRM_-feedback#109]

**Comment by ThomasLiu** [comment]
做成 上下一个周期

**Comment by jimmywong123** [comment]
统计可以自定义时间段查询了。
![image](https://user-images.githubusercontent.com/42126331/56421765-bb83a100-62d6-11e9-9ab6-0c0faebd2398.png)
