### ISSUE TITLE
对猎头部门最重要最紧急的系统功能！！！！

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#110]
目前我们无法统计数据，特别是推荐数、面试数、新建客户、签单客户，这几个数据很重要，最好是做一个统计功能，能够帮助我们统计某一段时间内的数据（日报，周报，月报的数据都需要在系统上完善）

![WechatIMG149](https://user-images.githubusercontent.com/47628230/55221019-8fc74b00-5243-11e9-9e18-eadb83a11c5a.png)

![WechatIMG150](https://user-images.githubusercontent.com/47628230/55221087-aff70a00-5243-11e9-8d6c-cf4c3ce6d8df.png)

**Comment by jimmywong123** [comment]
现在可以看到每位猎头的推荐与面试数量，并可以点击数字快速查看到是哪些简历。
岗位统计暂时先放一放。
![image](https://user-images.githubusercontent.com/42126331/55847846-87dda400-5b7d-11e9-94ff-21be192478dc.png)
