### ISSUE TITLE
把竞价过的企业单独列出来

### ISSUE THREAD

**Issue by kahyiu** [UReact/CRM_-feedback#111]

**Comment by jimmywong123** [comment]
现在客户界面多了一个有过竞价的选项了。
![image](https://user-images.githubusercontent.com/42126331/55394568-2d878680-5572-11e9-8b32-fa1db7f03c26.png)

**Comment by kahyiu** [comment]
没有啊
 
------------------------------------------------------------------
发件人：jimmywong123 <notifications@github.com>
发送时间：2019年4月2日(星期二) 18:08
收件人：UReact/CRM_feedback <CRM_feedback@noreply.github.com>
抄　送：Ella <ella.yao@hiredchina.com>; Author <author@noreply.github.com>
主　题：Re: [UReact/CRM_feedback] 把竞价过的企业单独列出来 (#111)

现在客户界面多了一个有过竞价的选项了。
[image]
