### ISSUE TITLE
客户页面的猎头岗位要有open和close岗位的区分

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#112]
![屏幕快照 2019-04-02 下午2 07 29](https://user-images.githubusercontent.com/47628230/55379813-c60d0f00-5550-11e9-8371-2c1061ef881b.png)

**Comment by jimmywong123** [comment]
现在企业信息内的职位列表也具有搜索功能了。
![image](https://user-images.githubusercontent.com/42126331/56113540-be0d9000-5f90-11e9-871a-4360f6cefa50.png)
