### ISSUE TITLE
crm的职位页面也需要和hiredchina的职位页面一样，要有搜索和状态分类功能

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#114]
https://www.hiredchina.com/hrs
https://crm.hiredchina.cn/clients/1
![屏幕快照 2019-04-02 下午2 45 32](https://user-images.githubusercontent.com/47628230/55381982-0cfe0300-5557-11e9-929c-1b44b3777007.png)
![屏幕快照 2019-04-02 下午2 45 58](https://user-images.githubusercontent.com/47628230/55381993-14bda780-5557-11e9-848f-92c9ddc64716.png)

**Comment by jimmywong123** [comment]
现在企业信息内的职位列表也具有搜索功能了。
![image](https://user-images.githubusercontent.com/42126331/56113540-be0d9000-5f90-11e9-871a-4360f6cefa50.png)
