### ISSUE TITLE
每个人才和客户都有自己的编号ID，搜索栏里面可以加上编号ID的搜索，

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#115]
![屏幕快照 2019-04-02 下午3 10 25](https://user-images.githubusercontent.com/47628230/55382927-75e67a80-5559-11e9-8ddc-6777841e8a12.png)

![屏幕快照 2019-04-02 下午3 08 26](https://user-images.githubusercontent.com/47628230/55382934-7a129800-5559-11e9-932c-1a37d3e821e8.png)

**Comment by jimmywong123** [comment]
现在客户和人才都支持对编号搜索了。
![image](https://user-images.githubusercontent.com/42126331/55449362-cfa08080-55fd-11e9-8d41-18a62d5edeea.png)
