### ISSUE TITLE
猎头客户的状态不仅需要有颜色区别显示，也需要根据不同的颜色状态分类

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#116]
![屏幕快照 2019-04-02 下午3 12 05](https://user-images.githubusercontent.com/47628230/55383110-f7d6a380-5559-11e9-9fc1-fabc6dd13f35.png)

**Comment by jimmywong123** [comment]
现在客户页面也可以根据客户状态进行搜索了。
![image](https://user-images.githubusercontent.com/42126331/56121503-d7b7d300-5fa2-11e9-9a95-6a57fe528f08.png)
