### ISSUE TITLE
搜索关键字需要高亮

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#117]
![屏幕快照 2019-04-02 下午5 00 37](https://user-images.githubusercontent.com/47628230/55390041-f791d480-5568-11e9-9357-446b8e42793b.png)
![屏幕快照 2019-04-02 下午5 01 02](https://user-images.githubusercontent.com/47628230/55390045-fa8cc500-5568-11e9-84be-b01824bc32c9.png)

**Comment by Victoryliu1160** [comment]
紧急

**Comment by jimmywong123** [comment]
现在搜索界面搜索时都会高亮关键字了，且点击进去后也会高亮关键字。
![image](https://user-images.githubusercontent.com/42126331/55950535-bb0c5a00-5c87-11e9-86f0-b600a2c70cfc.png)
![image](https://user-images.githubusercontent.com/42126331/55950606-e0996380-5c87-11e9-9664-4cc2b1e0c169.png)
