### ISSUE TITLE
职位列表 user搜索项，只要是有数据的内部系统用户列出来，没有数据的不需要

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#12]
![image](https://user-images.githubusercontent.com/3435615/52105803-2522d600-262b-11e9-8b1a-b85c7b1a9396.png)

**Comment by ThomasLiu** [comment]
再加一个统计的数字吧

**Comment by jimmywong123** [comment]
暂时忽略。
