### ISSUE TITLE
CRM系统内填写人才age 问题

### ISSUE THREAD

**Issue by kammylam** [UReact/CRM_-feedback#120]
现在CRM系统内年纪这一个栏目·，是必须要填的， 但是因为好多情况我们是不知道人才的年龄·。 所以建议加一个 “N/A"或 是不一定需要填写。 （因为现在如果没有填写，就会自动转为39岁），之后如果忘记了更改，就一直错误地以为是39岁了。
![1](https://user-images.githubusercontent.com/48010002/55701649-850c7300-5a06-11e9-91df-37b2a05ffeb2.jpg)

**Comment by jimmywong123** [comment]
现在不填写年龄的话，年龄就会为空，而不是之前的默认39岁。
