### ISSUE TITLE
客户的手机号邮箱号都绑定过，一直使用手机登陆，但最近登陆出现这个页面，crm系统也查不到

### ISSUE THREAD

**Issue by kahyiu** [UReact/CRM_-feedback#123]
![图片](https://user-images.githubusercontent.com/48083589/55777363-493edf80-5ad2-11e9-93c8-3e85e38356dc.png)
![图片](https://user-images.githubusercontent.com/48083589/55777380-53f97480-5ad2-11e9-8907-f70c9102b5a9.png)
![图片](https://user-images.githubusercontent.com/48083589/55777399-61aefa00-5ad2-11e9-8723-ca91deb98c79.png)

**Comment by ThomasLiu** [comment]
@kahyiu 亲，请提供是那个客户，客户链接，和这个人所声称的企业名，职位名，职位链接

**Comment by kahyiu** [comment]
不用啦！

------------------------------------------------------------------
发件人：Thomas Lau <notifications@github.com>
发送时间：2019年4月10日(星期三) 09:32
收件人：UReact/CRM_feedback <CRM_feedback@noreply.github.com>
抄　送：Ella <ella.yao@hiredchina.com>; Mention <mention@noreply.github.com>
主　题：Re: [UReact/CRM_feedback] 客户的手机号邮箱号都绑定过，一直使用手机登陆，但最近登陆出现这个页面，crm系统也查不到 (#123)

@kahyiu 亲，请提供是那个客户，客户链接，和这个人所声称的企业名，职位名，职位链接
