### ISSUE TITLE
标签要有多选选项，和标签候选人下面的批量操作

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#125]
![屏幕快照 2019-04-10 上午11 31 44](https://user-images.githubusercontent.com/47628230/55849723-43a1d200-5b84-11e9-96d5-fbb23e3a1afa.png)

**Comment by jimmywong123** [comment]
现在标签可以多选了，且支持批量操作了。
![image](https://user-images.githubusercontent.com/42126331/58321074-b377cd80-7e4f-11e9-80af-f8adfcdd8dfe.png)
