### ISSUE TITLE
统计 添加一个 总的充值和总的消费的 统计

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#128]

**Comment by ThomasLiu** [comment]
1、时间范围内的 单一周期，例 在月统计时，可以看到每天，年统计时，可以看到每月

**Comment by alexwang2019** [comment]
2、也要分 个人 和 企业。

**Comment by jimmywong123** [comment]
已添加总充值和总消费的。
![image](https://user-images.githubusercontent.com/42126331/56264506-4f0f7300-6119-11e9-8581-f7a74d700230.png)
