### ISSUE TITLE
我没有联系过的客户

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#129]
需求：我们要对一年前的旧用户做回归推广。

可以按照
1、创建时间
2、hr最后登录时间，
3、我的最后联系时间。
4、客户类型

5、是否有职位
6、是否有竞价

列表上 需要 职位数量，最后一个职位的创建时间和职位上的HR登录时间

**Comment by jimmywong123** [comment]
7，绑定和未绑定

**Comment by jimmywong123** [comment]
现在可按是否竞价，是否有职位，创建时间，hr登录时间，最后联系时间对客户进行搜索。
客户列表会显示职位数量以及hr最后打开职位的时间。
![image](https://user-images.githubusercontent.com/42126331/56257775-07c8b880-6100-11e9-8543-fcc9246eebaf.png)
