### ISSUE TITLE
人才填写联系记录保存 404

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#13]
![image](https://user-images.githubusercontent.com/3435615/52106027-0113c480-262c-11e9-9b81-e4e33f6fec14.png)

**Comment by ThomasLiu** [comment]
http://test.crm.hiredchina.cn/candidates/554

**Comment by jimmywong123** [comment]
这个是因为填写的时候没有选择职位。现在已经修复了。
