### ISSUE TITLE
我们可以在CRM系统上的候选人和客户页面设置一个地方，统一显示新注册的候选人和客户，及时查看，处理，开发。

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#130]
【我们可以在CRM系统上的候选人和客户页面设置一个地方，统一显示新注册的候选人和客户，及时查看，处理，开发。】
Alex在今天早上的早会开会说，我们有很多老的候选人和客户没有联系覆盖到；
我们也可以去查看覆盖每天在我们网站上新注册的客户和候选人，实际上，这些人也是最近在积极找工作或者招外籍的活跃群体（我们的开发目标群体之一）；

![屏幕快照 2019-04-15 下午5 14 12](https://user-images.githubusercontent.com/47628230/56121207-39c40880-5fa2-11e9-9269-bae6f1bef3f4.png)

**Comment by ThomasLiu** [comment]
@Victoryliu1160 看创建时间，都是按照创建时间排序的。
最前面就是 最新的人才和客户啦
