### ISSUE TITLE
讨论过后的【职位进程修改】的最终版

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#131]
Contacted with candidate
Sent CV to client
Rejected by client
Attended interview
Interview failed
Got offer letter，accepting offer
Got offer letter，rejecting offer
On board
Passed probation
Didn't pass probation

**Comment by Victoryliu1160** [comment]
![屏幕快照 2019-04-16 下午1 49 15](https://user-images.githubusercontent.com/47628230/56185773-41da8180-6050-11e9-8480-a3f149090ac4.png)

**Comment by jimmywong123** [comment]
已按要求修改了职位进程，在职位界面也会有相应的标签页。
![image](https://user-images.githubusercontent.com/42126331/56791375-837de000-6839-11e9-989d-a0b16457b571.png)
![image](https://user-images.githubusercontent.com/42126331/56791417-9a243700-6839-11e9-83ce-804dbb8332fc.png)
