### ISSUE TITLE
统计赠送金额

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#136]
1、全部赠送金额不对。
2、添加充值赠送
3、添加任务赠送
4、添加转发赠送
5、剩余未消费赠送总金额
6、剩余未消费充值总金额

**Comment by jimmywong123** [comment]
赠送金额现在会统计详细的充值赠送，转发赠送，任务赠送，以及其它赠送。
也会显示基础帐户余额以及赠送帐户余额。
![image](https://user-images.githubusercontent.com/42126331/56570542-baf84c80-65ed-11e9-90d1-31bdb240cce2.png)
