### ISSUE TITLE
近7天，近30天数据统计有问题

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#137]
当前周期，只有6天数据，不够7天，30天同样。
统计范围不对，今天看近7天数据应该不包含今天。30天的同样的问题

**Comment by jimmywong123** [comment]
近7天和近30天现在会从昨天开始算起。
![image](https://user-images.githubusercontent.com/42126331/56551033-dcd7dc00-65b9-11e9-90b2-13c4bfe311ac.png)
