### ISSUE TITLE
邮件营销内容

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#138]
1、生成兼职职位，非教育职位，专家职位，教育职位的邮件内容。
2、生成对应组合的人才邮箱清单。
3、生成有意向做兼职，有意向从事非教育类工作，专家工作，教育工作的人才邮件内容。
3、生成对应组合的HR邮箱清单。

**Comment by jimmywong123** [comment]
每周一周二会向人才与hr自动发送推广邮件，根据人才意向及企业职位为其推荐合适的职位与人才。
![image](https://user-images.githubusercontent.com/42126331/57275493-52bb6780-70d1-11e9-952c-ef07787882d1.png)

![image](https://user-images.githubusercontent.com/42126331/57275380-fa846580-70d0-11e9-917f-6f3299a3f431.png)
