### ISSUE TITLE
HR绑定微信，应该让我们能看见他的微信，这样对我们才有帮助

### ISSUE THREAD

**Issue by JohnWong1234** [UReact/CRM_-feedback#141]
![image](https://user-images.githubusercontent.com/49059974/56627473-82ea1b80-6678-11e9-8bf6-7b710d1d4a34.png)

**Comment by ThomasLiu** [comment]
@JohnWong1234  我们也想，问题是微信那边不会给我们微信号。

**Comment by JohnWong1234** [comment]
………………沉默
