### ISSUE TITLE
候选人筛选国籍的时候，需要多选

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#143]
候选人筛选国籍的时候，需要多选

![屏幕快照 2019-04-26 上午10 50 23](https://user-images.githubusercontent.com/47628230/56780260-2ff79c00-6811-11e9-8945-09794dfd1878.png)

**Comment by Victoryliu1160** [comment]
![屏幕快照 2019-04-26 上午10 50 23](https://user-images.githubusercontent.com/47628230/56780288-443b9900-6811-11e9-9711-0197913f8a2c.png)

**Comment by jimmywong123** [comment]
候选人界面国籍，地点，语言，职位都已支持多选。
![image](https://user-images.githubusercontent.com/42126331/56800125-e4fb7a00-684c-11e9-927f-fa38613e75d8.png)
