### ISSUE TITLE
40 是年龄区域筛选条件，而不是关键词搜索条件

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#144]
![屏幕快照 2019-04-26 上午10 54 39](https://user-images.githubusercontent.com/47628230/56780441-e065a000-6811-11e9-8d43-a6a8eeabfc20.png)
![屏幕快照 2019-04-26 上午10 54 04](https://user-images.githubusercontent.com/47628230/56780444-e3609080-6811-11e9-83e5-82b0d53b43b1.png)

**Comment by jimmywong123** [comment]
现在搜索人才时，年龄不会再出现在高亮项里。
