### ISSUE TITLE
紧急：猎头职位列表汇总表

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#146]
![WechatIMG243](https://user-images.githubusercontent.com/47628230/56882213-912fa180-6a95-11e9-95e4-3e110d1c6359.png)

**Comment by Victoryliu1160** [comment]
第一个表格要加点东西，不仅仅要知道顾问RS是谁，还要知道运营OP是谁

**Comment by jimmywong123** [comment]
现在可以根据职位对推荐，面试进行统计了。
![image](https://user-images.githubusercontent.com/42126331/57582916-63b70f00-74fd-11e9-8a06-a6f6ab5d980b.png)
