### ISSUE TITLE
紧急：猎头日常表格修复

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#147]
写了4的数据，只出现1个人 
Follow 选项独立开来，不要因为日期变化而变化

![屏幕快照 2019-04-29 下午3 41 20](https://user-images.githubusercontent.com/47628230/56882365-f2577500-6a95-11e9-996a-cbce55d35d6e.png)

**Comment by jimmywong123** [comment]
follow选项现在独立开了，不会因时间变化。
数字与人数对不上的问题已经修复。
