### ISSUE TITLE
人才界面显示他的竞价情况

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#151]
显示竞价创建时间，有客服或者HC管理权限的用户可以删除该竞价。
删除时自动加一条联系记录，记录该操作。

职位界面同样

**Comment by jimmywong123** [comment]
现在人才页面和职位页面会显示它们的竞价信息了，并且删除竞价后会自动生成一条记录。
![image](https://user-images.githubusercontent.com/42126331/57497073-bd0a1d00-7308-11e9-8b8f-92a1be4c608b.png)
