### ISSUE TITLE
角色管理界面修改

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#153]
实现改成 读取setting 的配置，把不需要的角色 剔除，其他的展示出来

点击人头直接进入 /users/:id

**Comment by jimmywong123** [comment]
角色界面现在会排除外部人员的权限。点击头像进入user界面。
![image](https://user-images.githubusercontent.com/42126331/57688472-1c9d5b00-7670-11e9-854e-301621acb3a8.png)
![image](https://user-images.githubusercontent.com/42126331/57689309-e1039080-7671-11e9-8ac0-42152ee73d63.png)
