### ISSUE TITLE
职位审核时HR反馈没有收到通知

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#155]
代码逻辑改为，在原有逻辑最后，如果没有找到任何可联系的联系方式，则把通知内容发到该职位上的邮箱地址。并且邮件内容提示其绑定邮箱和手机号码

**Comment by ThomasLiu** [comment]
顺便把哪里的代码重构一下，非常乱呢

**Comment by jimmywong123** [comment]
已修复没有收到通知bug，当找不到hr的联系方式时会发送至职位里的邮箱。
邮件内容的代码已重构至emailUtil，对于没有绑定手机和邮箱的hr在邮件中也会有相应提示，提示他们登录网站绑定联系方式。


![image](https://user-images.githubusercontent.com/42126331/58161532-ffd9d680-7cb2-11e9-96a2-90a52ee86f25.png)
