### ISSUE TITLE
一个客户有多个客户种类但是在列表上只显示了一个种类

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#156]
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/3435615/57433969-60592480-726c-11e9-9410-86813b605c00.png">
<img width="1461" alt="image" src="https://user-images.githubusercontent.com/3435615/57433979-664f0580-726c-11e9-907b-260d3fcb4eba.png">

**Comment by jimmywong123** [comment]
客户现在会显示完整的客户类型了。
![image](https://user-images.githubusercontent.com/42126331/57682008-72b7d180-7663-11e9-8252-68eb1e9784ea.png)
