### ISSUE TITLE
客户界面有权限的用户可以更改HR master

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#157]
当绑定的用户为多个的时候，有客服权限的用户，可以调整那个用户才是master

**Comment by jimmywong123** [comment]
现在可以点击change master按钮修改企业master了，只对admin，hiredchina manager和客服开放权限。
![image](https://user-images.githubusercontent.com/42126331/57680674-bceb8380-7660-11e9-9adb-fefd43c39d85.png)
![image](https://user-images.githubusercontent.com/42126331/57680690-c70d8200-7660-11e9-9b29-9def233eb653.png)
