### ISSUE TITLE
在客户界面的联系记录不用显示客户的链接

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#16]
![image](https://user-images.githubusercontent.com/3435615/52106210-daa25900-262c-11e9-9c0b-f0d60bc4c309.png)

**Comment by ThomasLiu** [comment]
![image](https://user-images.githubusercontent.com/3435615/52106313-3bca2c80-262d-11e9-946f-1931b07b5376.png)
在职位界面的联系记录，不需要显示这个职位链接
而且数据需要把客户的其他不是关于职位的联系联系记录也显示

**Comment by ThomasLiu** [comment]
![image](https://user-images.githubusercontent.com/3435615/52106332-53a1b080-262d-11e9-8052-d290fb021a01.png)

人才界面的联系记录不需要显示人才的链接

**Comment by jimmywong123** [comment]
现在人才界面的联系记录不再会显示人才链接；
职位界面的联系记录不再会显示职位链接；
公司界面的联系记录不再会显示公司链接；
