### ISSUE TITLE
列出跟进中的用户列表

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#161]
所有有follow 功能的（人才，客户，职位）
在右上角时间的区域显示 following 的用户列表
有crm管理员权限的用户，可以删除该follow 关系

**Comment by jimmywong123** [comment]
现在人才/客户/职位都会列出对应的跟进用户列表了，有管理权限的用户可以删除其跟进。
![image](https://user-images.githubusercontent.com/42126331/58228930-c8c2fe00-7d62-11e9-9f26-3aad4cfa0138.png)
