### ISSUE TITLE
联系记录功能没有按要求完成

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#168]
每条联系记录必须先选择联系人，才可以填写内容。

**Comment by jimmywong123** [comment]
现在企业的联系人页可以进行增删改操作了，且填写联系记录时需要选择联系人。
![image](https://user-images.githubusercontent.com/42126331/58872498-bb105f80-86f6-11e9-8c78-90c82ed5a887.png)
![image](https://user-images.githubusercontent.com/42126331/58872521-c794b800-86f6-11e9-99ff-4be5252c13f6.png)
