### ISSUE TITLE
客户类别加一个新类别，猎头潜在客户

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#169]
猎头部同事创建的客户，默认是这个类别

**Comment by jimmywong123** [comment]
猎头同时新建的客户默认为猎头客户，在跟进状态中可选有意向/无意向或者已合作。
![image](https://user-images.githubusercontent.com/42126331/58844192-bc1aa000-86a8-11e9-921e-122cd188ec79.png)
