### ISSUE TITLE
人才界面的 recommen 不需要显示人才那一栏

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#17]
![image](https://user-images.githubusercontent.com/3435615/52106372-79c75080-262d-11e9-9b0c-9aa8ff1cd4ae.png)

**Comment by ThomasLiu** [comment]
![image](https://user-images.githubusercontent.com/3435615/52106408-9f545a00-262d-11e9-95ca-0c0a12a4f30b.png)

同样职位的，也不需要显示职位那一栏

**Comment by jimmywong123** [comment]
现在人才界面的recommend不会显示人才链接，职位界面的recommend不会显示职位链接
![image](https://user-images.githubusercontent.com/42126331/52938362-786f8500-339c-11e9-9c3b-4ad704b2e9d2.png)
![image](https://user-images.githubusercontent.com/42126331/52938384-845b4700-339c-11e9-994a-c7cef29bbbc2.png)
