### ISSUE TITLE
候选人职位状态列表不全，应该再加多几条

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#21]
![screen shot 2019-02-14 at 6 08 58 pm](https://user-images.githubusercontent.com/47628230/52779979-3ab0ea80-3084-11e9-888e-fefb500fa173.png)
候选人职位状态列表不全，应该再加多几条：
1，Try to contact with his candidates
2，Upload his/her resume 
3，Upload his basic information
4，Sent his/her CV to client
5，Got the first round interview
6，Got the second round interview
7，Arranged the interview time
8，Got the feedback of interview
9，Got the offer from client
10，Start to work/ Onboard
11，Got fired

**Comment by jimmywong123** [comment]
这些状态都已经新增了
