### ISSUE TITLE
标签标记时要显示之前自己创建过的标签

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#23]
![screen shot 2019-02-14 at 6 20 14 pm](https://user-images.githubusercontent.com/47628230/52780500-3afdb580-3085-11e9-8555-be111b9c2bcb.png)

在给候选人创建标签时，要有自己之前创建过标签的列表，不然同一个意思的标签可能会有好几个，不好管理；最好可以有母标签和子标签的分类，更方便管理；

**Comment by jimmywong123** [comment]
![image](https://user-images.githubusercontent.com/42126331/53723216-2e10fc80-3ea2-11e9-8ffa-402638387b59.png)
现在新建标签会显示出你之前创建过的标签了。
母标签子标签以后再讨论。
