### ISSUE TITLE
商家列表账户下面需要显示标记，让我们在列表一下子知道他购买我们服务的状态

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#24]
![screen shot 2019-02-14 at 6 29 29 pm](https://user-images.githubusercontent.com/47628230/52781057-98463680-3086-11e9-9a8b-1016819bb864.png)
 现在只有显示是否有用户绑定，建议将用户的其他状态也显示在客户账号里面
例如：
购买了我们哪些产品/服务：gic 广告？ 猎头服务？
产品/服务状态：正在使用？已过期？

**Comment by jimmywong123** [comment]
![image](https://user-images.githubusercontent.com/42126331/54266457-61464080-45b2-11e9-83b6-fbeaef23d007.png)
现在会显示客户的分类了，如果已过期会显示成灰色。
