### ISSUE TITLE
新的企业客户行业细分可以再添加新的选项 例如：文化传媒公司/餐厅餐饮/语言翻译公司/旅游公司

### ISSUE THREAD

**Issue by LucyJoo** [UReact/CRM_-feedback#25]
列举这几个 是目前比较多见的 需要详细分类为一个行业的

**Comment by jimmywong123** [comment]
![image](https://user-images.githubusercontent.com/42126331/53724282-82b57700-3ea4-11e9-8933-f71d65c38e5e.png)
系统已增加了这几个选项。
