### ISSUE TITLE
人才界面 最下的用户信息 feedback 应该是从1可以不是0开始

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#26]
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/3435615/53231584-3c9e2d80-36c4-11e9-81a6-bceeeec51853.png">

**Comment by jimmywong123** [comment]
已修复
![image](https://user-images.githubusercontent.com/42126331/53344175-02938c80-394d-11e9-8e99-200a67e2cfb4.png)
