### ISSUE TITLE
客户列表，职位列表 Has user 的标记使用 抢眼一点的颜色

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#29]
![image](https://user-images.githubusercontent.com/3435615/53389846-edaa0e00-39cb-11e9-8455-438a10ba621c.png)

**Comment by jimmywong123** [comment]
现在hasuser，用户绑定都会有更显眼的标示了。
![image](https://user-images.githubusercontent.com/42126331/53400601-2b695f80-39e9-11e9-8050-e40edb276ba1.png)
