### ISSUE TITLE
Make records 多加一个折叠了的图标

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#31]
![image](https://user-images.githubusercontent.com/3435615/53389990-98bac780-39cc-11e9-9740-d5eae4c53cc8.png)

**Comment by jimmywong123** [comment]
![image](https://user-images.githubusercontent.com/42126331/53787081-9de1be80-3f58-11e9-8cc6-e5b93ebeae15.png)
make records现在添加了一个编辑图标。
