### ISSUE TITLE
紧急改进：猎头岗位有链接对接对应的客户

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#38]
可以专门开发出一块页面作为我们的猎头客户页面，里面需要可以填写客户的资料信息，和上传公司的文件比如组织架构图，这个猎头客户页面的链接可以安放在猎头岗位的页面，也可以作为信息补充安放在普通客户的页面。

**Comment by jimmywong123** [comment]
猎头职位可以关联到对应的企业了，企业内也开发了猎头职位栏目。
