### ISSUE TITLE
CRM内以下排序全部都错

### ISSUE THREAD

**Issue by kammylam** [UReact/CRM_-feedback#39]
![a](https://user-images.githubusercontent.com/48010002/53458317-97db7180-3a70-11e9-894c-af5195fadee3.jpg)
![b](https://user-images.githubusercontent.com/48010002/53458320-990c9e80-3a70-11e9-9e72-fb68e3a8bcdf.jpg)
![c](https://user-images.githubusercontent.com/48010002/53458322-9a3dcb80-3a70-11e9-8988-61ce9af3ea26.jpg)

**Comment by jimmywong123** [comment]
下拉菜单可以搜索，可以先用搜索功能；后续会按字母进行排序。

**Comment by jimmywong123** [comment]
现在这些下拉菜单会按字母排序了。
![2019-03-05 3 38 41](https://user-images.githubusercontent.com/42126331/53788593-3a0dc480-3f5d-11e9-8dae-889d80da24cd.png)
