### ISSUE TITLE
CRM内不能上传PDF format，另外如果上载错误没有delete功能

### ISSUE THREAD

**Issue by kammylam** [UReact/CRM_-feedback#40]
![2](https://user-images.githubusercontent.com/48010002/53458454-20f2a880-3a71-11e9-8a93-7cc96e07637d.png)

**Comment by jimmywong123** [comment]
现在已经支持pdf格式附件了。

**Comment by jimmywong123** [comment]
我这边没有出现过上传错误的问题。
