### ISSUE TITLE
URGENT-CRM candidate mark record问题

### ISSUE THREAD

**Issue by kammylam** [UReact/CRM_-feedback#42]
刚才收到份CV需要在record 加上一些资料。 但发现到上下都要选择才可以储存。 但要知道刚刚收到CV是没有什么状态可言的， 所以我认为是否一定选择？？？

如果强行需要选择，麻烦尽快加上 “Message" 给大家选择。但上面我认为没有需要
![1](https://user-images.githubusercontent.com/48010002/53459400-96ac4380-3a74-11e9-9c40-9c2e58ffa539.png)

**Comment by jimmywong123** [comment]
现在这两项已不再是必填项了。
