### ISSUE TITLE
URGENT-发给人才注册的链接问题，不能操作

### ISSUE THREAD

**Issue by kammylam** [UReact/CRM_-feedback#44]
当按邀请人才注册链接后，出现了空白的情况。
![send link](https://user-images.githubusercontent.com/48010002/53461176-aa5aa880-3a7a-11e9-855c-c1b958041daa.png)
![cand link](https://user-images.githubusercontent.com/48010002/53461183-ac246c00-3a7a-11e9-8f6a-f15089a7ddd8.jpg)

**Comment by ThomasLiu** [comment]
@kammylam 和人才了解他的手机型号

**Comment by jimmywong123** [comment]
人才的邀请链接已经修复了，现在可以正确打开。
