### ISSUE TITLE
审批客户时click网站问题

### ISSUE THREAD

**Issue by kammylam** [UReact/CRM_-feedback#46]
当审批客户的时候，平时按网站位置就可以看到客户的网站。 但现在click入去之后，就发现出现了404 这个版面 （但如果我用浏览器开客户网站是完全没有问题的）

![1](https://user-images.githubusercontent.com/48010002/53462594-4d152600-3a7f-11e9-9541-9b6adf3dadec.png)
![2](https://user-images.githubusercontent.com/48010002/53462596-4e465300-3a7f-11e9-996d-76575a262b46.png)
PS:这个是其中一个客户，之前有其他也是这样情况的

**Comment by jimmywong123** [comment]
此问题已修复。
