### ISSUE TITLE
紧急：个人record data 少了victory 的数据

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#50]
![screen shot 2019-02-27 at 7 03 03 pm](https://user-images.githubusercontent.com/47628230/53485953-7efbac00-3ac2-11e9-927f-b114306516a9.png)

**Comment by jimmywong123** [comment]
现在已经可以看到你的record了。
![image](https://user-images.githubusercontent.com/42126331/53793848-a098df80-3f69-11e9-9651-ec4694d3e874.png)
