### ISSUE TITLE
CRM系统最底下 其他产品 写成了 "在华外国人网"

### ISSUE THREAD

**Issue by LucyJoo** [UReact/CRM_-feedback#53]
![image](https://user-images.githubusercontent.com/47232757/53550992-13bde280-3b73-11e9-9eeb-8d8b5c000c5f.png)

**Comment by jimmywong123** [comment]
![image](https://user-images.githubusercontent.com/42126331/53795198-654be000-3f6c-11e9-8a66-07af7a05d0d5.png)
已经修复了
