### ISSUE TITLE
为什么创建联系人的领英链接，格式不正确？

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#54]
我直接复制粘贴，为什么创建联系人的领英链接，格式不正确？
![screen shot 2019-02-28 at 4 14 57 pm](https://user-images.githubusercontent.com/47628230/53551405-37cdf380-3b74-11e9-9d8e-b5756e7ed43e.png)

**Comment by jimmywong123** [comment]
现在已删除了对链接格式的检查。
