### ISSUE TITLE
Mark 求职者record问题

### ISSUE THREAD

**Issue by kammylam** [UReact/CRM_-feedback#55]
上面职位这个地方，需要设定一个可以不选择的按键， 因为有些人才只是发自己CV过来，我们什么还没有工作/职位介绍给他， 有怎么选择？  所以请改为选择性，否则不能写记录！
![Uploading 1.png…]()

**Comment by ThomasLiu** [comment]
@kammylam 亲，你的图片还没有上传完，你就提交了。我们看不到你上传的图片呢

**Comment by kammylam** [comment]
亲。。不好意思，可能我太心急，我是说这个位置呀！
![1](https://user-images.githubusercontent.com/48010002/53612924-5503d000-3c0f-11e9-98a1-28ea1d50d22a.png)

**Comment by jimmywong123** [comment]
现在record上面两项都不在是必填项了，已经修复。
