### ISSUE TITLE
创建新的候选人，在resume temp 加东西，最后不会出现，要重新更改才会出现

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#56]

**Comment by ThomasLiu** [comment]
@Victoryliu1160 亲，请提供截图（截图包含地址链接），我们测试了在其他人才中没有出现你所说的问题。我们不确定我们测试和你说的是否是同一个！！！

**Comment by jimmywong123** [comment]
现在创建简历时会正确的添加resumeTemp
![image](https://user-images.githubusercontent.com/42126331/53796291-ca083a00-3f6e-11e9-8aae-54505c58500e.png)
