### ISSUE TITLE
人才联系记录时间有问题

### ISSUE THREAD

**Issue by kammylam** [UReact/CRM_-feedback#57]
当我在人才主页看到的联系记录时间与click入资料库内的时间不同。
![a](https://user-images.githubusercontent.com/48010002/53565620-e7b35900-3b94-11e9-876b-a0ab7bab6c10.png)
![b](https://user-images.githubusercontent.com/48010002/53565622-e97d1c80-3b94-11e9-8812-eeac137e584b.png)

**Comment by jimmywong123** [comment]
现在人才主页会显示正确的联系时间。
![image](https://user-images.githubusercontent.com/42126331/53798890-202bac00-3f74-11e9-9364-2dfef0765507.png)
