### ISSUE TITLE
有些新的客户网站是没有问题的，但发布之后按网站链接是空白页

### ISSUE THREAD

**Issue by kammylam** [UReact/CRM_-feedback#59]
有些新的客户网站是没有问题的，但发布之后按网站链接是空白页

![1](https://user-images.githubusercontent.com/48010002/53606176-d6019e00-3bf4-11e9-877d-bd6bc57c4e8b.png)
![2](https://user-images.githubusercontent.com/48010002/53606178-d7cb6180-3bf4-11e9-87ab-b4b43956bb0c.png)

**Comment by jimmywong123** [comment]
这个是hiredchina网页的问题，应当提交到https://github.com/UReact/HC_feedback/issues

**Comment by jimmywong123** [comment]
crm新建职位时没有保存相关公司信息，数据库还需update一次。

**Comment by jimmywong123** [comment]
现在已经修复了
