### ISSUE TITLE
人才界面 no data 多一点提示，这是什么no data

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#6]
![image](https://user-images.githubusercontent.com/3435615/52104156-1e449500-2624-11e9-8ac9-fe93e10813c6.png)

**Comment by jimmywong123** [comment]
现在nodata会给出具体的提示。
![image](https://user-images.githubusercontent.com/42126331/56335418-07e3b980-61cf-11e9-9696-f2ea55d8f11d.png)
