### ISSUE TITLE
网站不稳定，时间出现的页面 500 server reporting error

### ISSUE THREAD

**Issue by kammylam** [UReact/CRM_-feedback#60]
![1](https://user-images.githubusercontent.com/48010002/53611357-43b7c500-3c09-11e9-9a34-7a52ec54ad5e.png)

**Comment by ThomasLiu** [comment]
@kammylam  亲，请提供 你在那个界面（截图），点止了什么，之后才出现这个。我们才可以帮你解决到问题。你这么一句话，爱莫能助的

**Comment by kammylam** [comment]
我有试过几次，当审批完客户，然后发布职位到网站后，跟住我就入HC网站，他就有这个页面出现。有时我是一打开网站再按入去就出现。
