### ISSUE TITLE
新建联系人，简历里面加东西，最后没显示

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#63]
![screen shot 2019-03-01 at 2 29 00 pm](https://user-images.githubusercontent.com/47628230/53620618-8cce4000-3c2e-11e9-8680-198d59ee84b0.png)

![screen shot 2019-03-01 at 2 26 17 pm](https://user-images.githubusercontent.com/47628230/53620643-a53e5a80-3c2e-11e9-916f-d5cbf0b84ffd.png)

**Comment by ThomasLiu** [comment]
@Victoryliu1160 请把操作流程截图，现在这样的描述我们没法跟进

**Comment by Victoryliu1160** [comment]
这两张就是流程图，顺序反了。
