### ISSUE TITLE
给候选人创建标签时，需要显示之前创建过的标签，不然会重复创建

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#65]
![screen shot 2019-03-03 at 2 42 19 pm](https://user-images.githubusercontent.com/47628230/53691955-da7bb180-3dc2-11e9-9e91-8e2e4a3afce1.png)

**Comment by jimmywong123** [comment]
现在创建标签时会显示你之前创建过的标签了。
![image](https://user-images.githubusercontent.com/42126331/53785871-e5664b80-3f54-11e9-980b-da344d4d5cc7.png)
