### ISSUE TITLE
给客户发绑定邀请链接 微信分享时候不能生成链接条 而是很长的网址链接

### ISSUE THREAD

**Issue by LucyJoo** [UReact/CRM_-feedback#69]
![image](https://user-images.githubusercontent.com/47232757/53773860-116ad800-3f27-11e9-92bf-572a138c4a56.png)
![image](https://user-images.githubusercontent.com/47232757/53773891-26e00200-3f27-11e9-95b3-e3f0043d9f06.png)

**Comment by ThomasLiu** [comment]
@jimmywong123  邀请链接下面增加 二维码模式

**Comment by ThomasLiu** [comment]
@LucyJoo 功能正常
