### ISSUE TITLE
客户审核，选择了reject 后，状态还是 Being reviewed，刷新界面也是一样

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#7]
![image](https://user-images.githubusercontent.com/3435615/52104224-64015d80-2624-11e9-9c57-df56a503025c.png)
![image](https://user-images.githubusercontent.com/3435615/52104239-77acc400-2624-11e9-855d-4c4cefd36337.png)

**Comment by ThomasLiu** [comment]
职位审核也是一样

**Comment by jimmywong123** [comment]
update国际化时同步修改它的key，这个已经修复了。
