### ISSUE TITLE
职位界面需要显示 该职位的竞价情况

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#70]

**Comment by jimmywong123** [comment]
现在职位列表和职位界面都会显示它的竞价情况了。
![image](https://user-images.githubusercontent.com/42126331/53777789-7af1e300-3f35-11e9-8eb5-bedd0c416248.png)
![image](https://user-images.githubusercontent.com/42126331/53777806-893fff00-3f35-11e9-8a89-81e14100457c.png)
