### ISSUE TITLE
猎头岗位页面的record选项要加日期筛选

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#73]
![screen shot 2019-03-06 at 10 58 31 am](https://user-images.githubusercontent.com/47628230/53853731-a215e680-4001-11e9-8b17-d4f5567cf011.png)

**Comment by Victoryliu1160** [comment]
日期筛选，和姓名筛选

**Comment by jimmywong123** [comment]
现在record列表较多时会出现搜索框，可以按创建者和时间进行搜索。
![image](https://user-images.githubusercontent.com/42126331/53929128-ac9ab380-40c7-11e9-83b7-1074af83206d.png)
