### ISSUE TITLE
CRM系统 创建客户档案 logo上传失败 浏览器无响应

### ISSUE THREAD

**Issue by LucyJoo** [UReact/CRM_-feedback#74]

**Comment by LucyJoo** [comment]
火狐、谷歌、QQ浏览器通通不行 即使去掉了拦截情况 还是无法加载图片或者上传不了

**Comment by LucyJoo** [comment]
![image](https://user-images.githubusercontent.com/47232757/53874429-600a9600-403d-11e9-9f46-6656f74aaa5d.png)

**Comment by jimmywong123** [comment]
已经修复。
