### ISSUE TITLE
紧急：猎头职位页面，应该加上对应的客户链接；客户页面，应该加上对应的猎头岗位链接

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#77]
![screen shot 2019-03-08 at 10 31 55 am](https://user-images.githubusercontent.com/47628230/54019246-ac80dd80-41c5-11e9-81fc-a4cdeaf97fe3.png)
![screen shot 2019-03-08 at 5 14 09 pm](https://user-images.githubusercontent.com/47628230/54019254-b276be80-41c5-11e9-9fb5-66c63adb8cb6.png)

**Comment by jimmywong123** [comment]
现在在职位界面可以关联到对应的客户，在客户界面新增了猎头职位栏目。
![image](https://user-images.githubusercontent.com/42126331/54588141-1ec2af00-4a5d-11e9-8861-80dac5f9ea0d.png)
![image](https://user-images.githubusercontent.com/42126331/54588304-8a0c8100-4a5d-11e9-8ce3-2fbf208b322c.png)
