### ISSUE TITLE
标签后面要有括号显示有多少个人加了这个标签

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#81]
![屏幕快照 2019-03-12 下午7 40 15的副本](https://user-images.githubusercontent.com/47628230/54197457-fbe54780-44fe-11e9-840f-11dc45939c70.png)

**Comment by jimmywong123** [comment]
label页现在会显示具体的数量了。
![image](https://user-images.githubusercontent.com/42126331/56488520-2d472f00-6511-11e9-8981-6c612d138991.png)
