### ISSUE TITLE
删除临时标签：在标签页面删除标签（所有和这个标签关联的人都要删除）

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#83]
有时会创建临时标签，用了过段时间就删掉；
现在想要删除大标签，只能一个个点进人才页面删除，太麻烦；
希望可以在标签页面，直接删标签，有这个标签关联的人直接删除。
![屏幕快照 2019-03-13 上午10 49 55](https://user-images.githubusercontent.com/47628230/54250655-9b4a1f00-457f-11e9-805a-3bfe68866667.png)
![屏幕快照 2019-03-13 上午10 49 55](https://user-images.githubusercontent.com/47628230/54250669-ab61fe80-457f-11e9-8be1-d984344707cd.png)

**Comment by Victoryliu1160** [comment]
同时要开放给标签重命名的权限

**Comment by jimmywong123** [comment]
现在可以在label界面一次性删除与此label关联的简历关系，也可以批量添加标签。
![image](https://user-images.githubusercontent.com/42126331/58320821-26347900-7e4f-11e9-85de-9adff84befdc.png)
![image](https://user-images.githubusercontent.com/42126331/58320942-609e1600-7e4f-11e9-84d9-df8fe5bd2c02.png)
