### ISSUE TITLE
CRM HC与GC Client 区分 （希望能把之前的数据也进行分类）

### ISSUE THREAD

**Issue by LucyJoo** [UReact/CRM_-feedback#84]
方便我们后续联系跟进 更加方便 GIC部门一天的联系记录多达二十几条 所以说之前的数据都要做区分标识是很有必要的...

![image](https://user-images.githubusercontent.com/47232757/54250726-e6fcc880-457f-11e9-8f56-dc38cb9db962.png)

**Comment by jimmywong123** [comment]
之前的数据全部分类了。
![image](https://user-images.githubusercontent.com/42126331/54679095-733f5a80-4b41-11e9-81ee-11ad8f8a4b02.png)
