### ISSUE TITLE
刊登HC自己公司广告出现问题，按TOP UP后就自动弹了去付款版面，之前所有刊登了的资料没有了

### ISSUE THREAD

**Issue by kammylam** [UReact/CRM_-feedback#85]
刊登HC自己公司广告出现问题，（因为现在每个广告都需要付款）。 按TOP UP后就自动弹了去付款版面，之前所有刊登了的资料没有了。。。。已经试过了3次都是这个情况！！ 救命！
![1](https://user-images.githubusercontent.com/48010002/54251394-072d8700-4582-11e9-8bcd-884f295a7461.png)

**Comment by ThomasLiu** [comment]
@kammylam  亲，不用点 topup 的
