### ISSUE TITLE
客户未审批的广告，同一个时间重复了3次

### ISSUE THREAD

**Issue by kammylam** [UReact/CRM_-feedback#86]
![1](https://user-images.githubusercontent.com/48010002/54254778-0a2f7400-4590-11e9-9134-d1647d6763bc.png)

**Comment by jimmywong123** [comment]
已删除多余的职位。
这个有可能是客户在提交职位时，反复点击提交键或者反复按enter键，同时程序没有控制好，导致的职位反复提交。
