### ISSUE TITLE
404

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#87]
填候选人微信信息提交之后，显示404
![屏幕快照 2019-03-13 下午2 49 46](https://user-images.githubusercontent.com/47628230/54258997-4b7b5000-459f-11e9-9668-83564a235e27.png)
![屏幕快照 2019-03-13 下午2 49 52](https://user-images.githubusercontent.com/47628230/54259005-51713100-459f-11e9-9b6e-a4346d0a52c8.png)

**Comment by jimmywong123** [comment]
已经修复。
