### ISSUE TITLE
标签里面的联系人或客户排序顺序，要按照和标签关联的时间顺序排序

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#91]
标签里面的联系人或客户排序顺序，要按照和标签关联的时间顺序排序，而不是按照原本创建候选人或客户的时间排序！！

![屏幕快照 2019-03-13 下午9 41 31](https://user-images.githubusercontent.com/47628230/54283562-463af700-45d9-11e9-992c-641dc254a353.png)

**Comment by Victoryliu1160** [comment]
可以按倒序的顺序排序，最新关联的排在最前面
![屏幕快照 2019-03-13 下午9 47 46](https://user-images.githubusercontent.com/47628230/54283795-b8134080-45d9-11e9-9eea-f3164825e674.png)

**Comment by jimmywong123** [comment]
暂时难以实现
