### ISSUE TITLE
候选人看不到余额

### ISSUE THREAD

**Issue by kahyiu** [UReact/CRM_-feedback#92]
![图片](https://user-images.githubusercontent.com/48083589/54330432-a4ef8780-4650-11e9-803c-09e5acd83977.png)

**Comment by jimmywong123** [comment]
现在可以看到候选人余额了。
![image](https://user-images.githubusercontent.com/42126331/54590453-21c09e00-4a63-11e9-9f44-23f10e3912f8.png)
