### ISSUE TITLE
建议创建职位里头语言选项可以添加：泰语/阿拉伯语 

### ISSUE THREAD

**Issue by LucyJoo** [UReact/CRM_-feedback#93]
![image](https://user-images.githubusercontent.com/47232757/54417305-b9a94980-473c-11e9-911c-9788509f8f0f.png)

目前有关于这两个语言的岗位需求日益增多 觉得有必要添加

**Comment by kammylam** [comment]
Lucy, 现在如果想加语言或地区等，可以告诉我，因为现在我有权限可以加，不用等IT同事。thx！
