### ISSUE TITLE
搜索界面调整

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_-feedback#95]
所有的搜索界面换成tab 的方式
客户搜索
* All
   搜索条件：
   + 关键词搜索（客户名字，客户中文名，固话，网站，line）
   + 行业
   + 地区
* 按HR搜索 
* 按用户分类（可以换成其他用户）
   搜索条件：
   + 单选：创建，联系过，follow，查看过
* 我创建的
* 我联系过的
* 我follow的
* 我查看过的
* HC客户
  搜索条件：
   + 关键词搜索（客户名字，客户中文名，固话，网站，line）
   + 关联用户联系方式
   + 行业
   + 地区
* GIC客户
  搜索条件：
   + 关键词搜索（客户名字，客户中文名，固话，网站，line）
   + 关联用户联系方式
   + 行业
   + 地区
* 猎头客户
  搜索条件：
   + 关键词搜索（客户名字，客户中文名，固话，网站，line）
   + 关联用户联系方式
   + 行业
   + 地区
* 待审核 （有hc 管理权限）
* 已经审核 （有hc 管理权限）
* 不通过 （有hc 管理权限）
* 余额为零客户
* 余额大于零的客户

人才搜索
* All
  搜索条件：
   + 关键词搜索（姓，名，手机，邮箱，微信，line， linkedin，headline）
   + 国籍
   + 当前城市
   + 语言 和 熟练程度
   + 职位类别
   + 简历搜索（简历内的概括，工作经历描述和标题，mark临时简历）
   + 期待工作地点
   + 期待工作类型
   + 期待工作方式

* 按用户分类（可以换成其他用户）
   搜索条件：
   + 单选：创建，联系过，follow，查看过
* 我创建的
* 我联系过的
* 我follow的
* 我查看过的
recommend 的所有，可以按照人才名字搜索，职位选择（数字）
* 曾经发送过的
* 曾经有面试的
* 曾经上班过的

* 余额为零人才
* 余额大于零的人才

职位搜索
* All 
   搜索条件：
   + 关键词搜索（公司名，职位titlte，line，公司的line）
   + 工作经验
   + 职位类别
   + 地区
* 猎头职位（数字）
  + 关键词搜索（公司名，职位titlte，line，公司的line）

* 待审核 （有hc 管理权限）
* 已经审核 （有hc 管理权限）
* 不通过 （有hc 管理权限）
* 暂停 （有hc 管理权限）

**Comment by ThomasLiu** [comment]
客户搜索 HC，HH，GIC 的统计和搜索失效

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/3435615/55299078-d3989b00-5463-11e9-89c4-88e32fe91646.png">

**Comment by jimmywong123** [comment]
已添加
![图片](https://user-images.githubusercontent.com/42126331/55473974-92121680-5642-11e9-9a91-d222b76fe9f8.png)
![图片](https://user-images.githubusercontent.com/42126331/55473986-9dfdd880-5642-11e9-9452-123d7f31ca88.png)
![图片](https://user-images.githubusercontent.com/42126331/55473996-a7874080-5642-11e9-8548-56767c0844ec.png)
