### ISSUE TITLE
职位页面出现的record要分类

### ISSUE THREAD

**Issue by Victoryliu1160** [UReact/CRM_-feedback#96]
职位页面出现的record包含：
RS在人才页面写的record和OP在职位页面写的record
现在混在一起了，需要区分
![屏幕快照 2019-03-20 下午6 16 32](https://user-images.githubusercontent.com/47628230/54676920-c95dcf00-4b3c-11e9-94df-58554c29013f.png)

**Comment by ThomasLiu** [comment]
客户界面
* 按创建者
* 按类型
* 按职位
* 按推荐进度

职位界面 
* 按创建者
* 按类型
* 按推荐进度
* 按人才

人才界面
* 按创建者
* 按类型
* 按职位
* 按客户

**Comment by jimmywong123** [comment]
现在职位界面只会出现关于职位的record，人才界面只会出现关于人才的record，公司界面只会出现关于公司的record。
